### ISSUE TITLE
Ability to navigate with ctrl+n/p

### ISSUE THREAD

**Issue by dlvhdr** [omranjamal/mono-cd#1]
Thanks for this awesome program :)

I would like to have the ability to navigate with control+n/p which are popular vim keybindings for navigating up/down the list.

**Comment by omranjamal** [comment]
Interesting, I might need to sleep on it a bit, but seems harmless enough.

**Comment by omranjamal** [comment]
Hi @dlvhdr, I added this to the `v1.2.0` release. Use the command below to upgrade.

```bash
curl -L "https://github.com/omranjamal/mono-cd/releases/latest/download/install.sh" | sh -
```

Have fun!
